spring:
  datasource:
    # url: jdbc:postgresql://localhost:5432/jwt_security
    url: jdbc:mysql://127.0.0.1:3306/jwt_security
    username: root
    password: C8aJEVCCvSA1VFi8
    # driver-class-name: org.postgresql.Driver
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: false
    # database: postgresql
    database: mysql
    # database-platform: org.hibernate.dialect.PostgreSQLDialect
    # database-platform: org.hibernate.dialect.MySQL8Dialect

application:
  security:
    jwt:
      secret-key: 404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
      expiration: 86400000 # a day
      refresh-token:
        expiration: 604800000 # 7 days

server:
  port: 9010
